# site.yml
#Problemen met pullen
---
- hosts: Web001
  become: true
  vars_files:
   - host_vars/Web001.yml
  roles:
    - bertvv.rh-base
    - bertvv.httpd
    - bertvv.mariadb
    - bertvv.drupal
    #- geerlingguy.git
    #- geerlingguy.drush
    #- geerlingguy.drupal
    #- bertvv.wordpress
  
- hosts: Monitoring001
  become: true
  vars_files:
   - host_vars/Monitoring001.yml
  roles:
    - bertvv.rh-base
    - metricbeat